### ISSUE TITLE
Python module does not build with Python 3.12

### ISSUE THREAD

**Issue by dhdaines** [garvys-org/rustfst#283]
This is fixed by #281 but here's an issue describing the problem.  It is because you have pinned `setuptools` to a much too old version.  When running `pip install .` in `rustfst-python`, this happens (among a longer stacktrace):
```
        File "/tmp/pip-build-env-wrfvjvka/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-wrfvjvka/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-wrfvjvka/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
```
